### ISSUE TITLE
Extension airdcpp-share-monitor has exited

### ISSUE THREAD

**Issue by bobo-j** [airdcpp-web/airdcpp-share-monitor#1]
when I start the extension it has exited and get me this error in error.log file:

fs.js:1384
    throw error;
    ^

Error: watch /media/boris/1.5TB/DC TEMP/Arzemju muzika/DeVision/Singles/10 Strange Affection (2CD Single) 1998/Disc1 Strange Affection 1998 ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at /media/boris/Archive/airdcpp-webclient_2.10b78_webui_2.10b5/config/extensions/airdcpp-share-monitor/package/dist/main.js:1:48034
    at e (/media/boris/Archive/airdcpp-webclient_2.10b78_webui_2.10b5/config/extensions/airdcpp-share-monitor/package/dist/main.js:1:41335)
    at b.watchDirectory (/media/boris/Archive/airdcpp-webclient_2.10b78_webui_2.10b5/config/extensions/airdcpp-share-monitor/package/dist/main.js:1:47919)
    at /media/boris/Archive/airdcpp-webclient_2.10b78_webui_2.10b5/config/extensions/airdcpp-share-monitor/package/dist/main.js:1:48184
    at /media/boris/Archive/airdcpp-webclient_2.10b78_webui_2.10b5/config/extensions/airdcpp-share-monitor/package/dist/main.js:1:43556
    at Array.forEach (<anonymous>)
    at /media/boris/Archive/airdcpp-webclient_2.10b78_webui_2.10b5/config/extensions/airdcpp-share-monitor/package/dist/main.js:1:43501

I use AirDC++w 2.10.0b-78-ge65f x86_64 on Linux Mint

**Comment by maksis** [comment]
What's the number of total directories (including all subdirectories) that you are sharing?

**Comment by maksis** [comment]
Could you also post the output of the following shell command: `cat /proc/sys/fs/inotify/max_user_watches`

**Comment by bobo-j** [comment]
The number of directories are 9799
The output for "cat /proc/sys/fs/inotify/max_user_watches"  is 8192

**Comment by maksis** [comment]
You could follow https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit to increase the limit for maximum watchers to be greater than the number of directories in share

**Comment by bobo-j** [comment]
It seems that was the problem. I increase the watches limit to 512K and now is working! Big Thanks!

**Comment by maksis** [comment]
This issue has now been documented in the README. Crashing isn't the best way to handle such errors, but the watcher library used by the extension doesn't currently have support for catching them.
