### ISSUE TITLE
Share don't refreshed if symlink created

### ISSUE THREAD

**Issue by infectormp** [airdcpp-web/airdcpp-share-monitor#4]
In shared directory I created symlink to folder on another drive and it doesn't trigger airdc to refresh it.

**Comment by maksis** [comment]
Please see the troubleshooting section: https://github.com/airdcpp-web/airdcpp-share-monitor#troubleshooting

How did you create the symlink?

**Comment by infectormp** [comment]
I created symlink using tool NTFS Links 
`23.01.2023  21:43    <JUNCTION>     Hello_Strange [\??\i:\labels\Hello_Strange]`

![image](https://user-images.githubusercontent.com/9958813/214141755-e288bea5-2585-425a-a08c-37bd82cf690e.png)

but in the filelist it sill doesn't exist
![image](https://user-images.githubusercontent.com/9958813/214141482-33c79fcd-1be5-44bd-8e59-b1fd2060fe71.png)
and no any entry in system log too

**Comment by maksis** [comment]
> and no any entry in system log too

That's expected, you need to follow the troubleshooting guide instead

**Comment by infectormp** [comment]
I deleted symlink and create again
output.log:
[2023-1-23 23:35:47:902] DELETE, IGNORE: path J:\labels\Hello_Strange (not shared)
[2023-1-23 23:36:42:870] CHANGE, SKIP: path J:\labels\Hello_Strange, modified 8458581.649658203 ms ago
[2023-1-23 23:36:42:916] CHANGE, SKIP: path J:\labels\Hello_Strange, modified 8458627.649658203 ms ago

**Comment by infectormp** [comment]
Then I created normal dir 
[2023-1-23 23:39:28:318] CHANGE, ACCEPT: directory J:\labels\Hello_Strange\, modified 0.05029296875 ms ago

**Comment by maksis** [comment]
So it won't refresh the directory because the last modified date is too old

**Comment by infectormp** [comment]
look like this is NTFS\Windows behavior, symlink do not show real ctime\mtime. 
and also, there are 2 differences between symlink and regular dir. For symlink it says - path, for dir - directory, so I think it can be solved by not checking last modified date for PATH

**Comment by maksis** [comment]
I can reproduce the issue but I'm not sure how it could be easily fixed. The extension checks the last modified date because the Node.js will also fire change events also when the file access date has changed (as those shouldn't trigger refreshes). Looks like the access date is also updated when the link is created so even that can't be used to determine that something is different.

**Comment by infectormp** [comment]
Well, when I created symlink extension handled it as a `path` (CHANGE, SKIP: path), but regular dir is handled as a `directory` (CHANGE, ACCEPT: directory).  So maybe we can ignore modify date for `path`.  Also, it can be an optional future.

**Comment by maksis** [comment]
> Well, when I created symlink extension handled it as a path (CHANGE, SKIP: path), but regular dir is handled as a directory (CHANGE, ACCEPT: directory). So maybe we can ignore modify date for path. Also, it can be an optional future.

That's not the case, it just uses a single log message there. The path can be either a file or a directory and it's still a directory.

**Comment by infectormp** [comment]
It seems better to use the USN journal in Windows to handle fs modification, as [Everything](https://www.voidtools.com/) does.

**Comment by maksis** [comment]
> It seems better to use the USN journal in Windows to handle fs modification, as [Everything](https://www.voidtools.com/) does.

Maybe, but that's not really within the scope of this project. This is a cross-platform file watcher extension written in JavaScript that doesn't implement any low-level file watcher code. The approach has its limitations but it works well enough for common use cases. It would be better to write a new extension if a totally different way of tracking modifications is needed.
