### ISSUE TITLE
Operations with directory not handled if it ware made inside symlink directory

### ISSUE THREAD

**Issue by infectormp** [airdcpp-web/airdcpp-share-monitor#5]
I have x:\shared_directory\symlink_directory <-symlink to another drive.
After I created a new directory inside symlink_directory (x:\shared_directory\symlink_directory\new_directory) this was not handled by share monitor. There are no any entry in output.log about new directory. 

In AirDC I use ![image](https://user-images.githubusercontent.com/9958813/215118237-735d2628-e858-4543-874c-a594f779ae35.png) option

**Comment by infectormp** [comment]
Delete operation also not handled.

**Comment by maksis** [comment]
Do you see anything in `error.log`?

**Comment by infectormp** [comment]
No, it is empty.

**Comment by maksis** [comment]
Looks like the extension won't receive any change event from the system/Node.js. I'm afraid that there's no way to solve this.
